WIP odemis-select-channel: handle DEB822 repo format

diff --git a/install/linux/usr/bin/odemis-select-channel b/install/linux/usr/bin/odemis-select-channel
--- a/install/linux/usr/bin/odemis-select-channel
+++ b/install/linux/usr/bin/odemis-select-channel
@@ -21,6 +21,8 @@ get_home_dir() {
 
 USER_HOME=$(get_home_dir)
 ODEMIS_DEV_PATH="$USER_HOME/development/odemis"
+PPA_PROPOSED_NAME="delmic-soft/odemis-proposed"
+PPA_STABLE_NAME="delmic-soft/odemis"
 
 # Detect the current channel of Odemis.
 # Returns "stable", "proposed", or "dev".
@@ -31,12 +33,46 @@ detect_channel() {
         return
     fi
 
-    # If the "odemis-proposed" PPA is active, it's "proposed", otherwise "stable".
-    if grep -q -r -E '^deb.*delmic-soft/odemis-proposed' /etc/apt/sources.list /etc/apt/sources.list.d/*.list 2>/dev/null; then
+    # apt-get indextargets automatically converts .list and .sources files to DEB822 format,
+    # and only outputs the enabled ones. That simplifies the parsing.
+    if apt-get indextargets --format '$(URI)' | grep -q "/${PPA_PROPOSED_NAME}/"; then
         echo "proposed"
-    else
+    else  # It must be the stable channel.
+        # TODO: check the odemis package is installed?
+        # For now, we assume that if this program is running, then Odemis was installed.
         echo "stable"
     fi
+
+#    # 1. Check .list and sources.list files (ignoring commented lines)
+#    if grep -qrE "^[[:space:]]*deb .*${PPA_PROPOSED_PATTERN}" /etc/apt/sources.list /etc/apt/sources.list.d/*.list 2>/dev/null; then
+#        echo "proposed"
+#        exit 0
+#    fi
+#    # 2. Check .sources files (DEB822 format, which is used in Ubuntu 24.04 and later)
+#    for file in /etc/apt/sources.list.d/*.sources; do
+#        [ -f "$file" ] || continue
+#
+#        # TODO: for now, it only handle properly files with a single repo.
+#        # An alternative would be to use "apt-get indextargets --format '$(URI)' | grep {PPA_PATTERN}"
+#        # It converts everything to DEB822, and only shows the enabled ones.
+#        # Works on Ubuntu 20.04 and later.
+#
+#        # Get the Enabled field (default to yes if missing)
+#        enabled=$(grep -i '^Enabled:' "$file" | tail -n1 | awk '{print tolower($2)}')
+#        [ -z "$enabled" ] && enabled="yes"
+#
+#        if [ "$enabled" = "no" ]; then
+#            continue
+#        fi
+#
+#        # Check if URIs field contains the PPA
+#        if grep -qE "^URIs:.*${PPA_PATTERN}" "$file"; then
+#            echo "proposed"
+#            exit 0
+#        fi
+#
+#    done
+
 }
 
 # Activate the "dev" channel.
@@ -56,8 +92,16 @@ enable_dev_mode() {
         chown -R "$owner":"$owner" "$ODEMIS_DEV_PATH"
     fi
 
+    # Often, there is a DEVPATH=... line, which is used by the PYTHONPATH line
+    # If someone has commented it out, we need to uncomment it.
+    if grep -q '^#\s*DEVPATH=' /etc/odemis.conf 2>/dev/null; then
+        echo "Enabling the DEVPATH line in /etc/odemis.conf"
+        sudo sed -i 's/^#\s*\(DEVPATH=.*\)/\1/' /etc/odemis.conf
+    fi
+
     # Uncomment PYTHONPATH line in /etc/odemis.conf if commented out
     if grep -q '^#\s*PYTHONPATH=' /etc/odemis.conf 2>/dev/null; then
+        echo "Enabling the PYTHONPATH line in /etc/odemis.conf"
         sudo sed -i 's/^#\s*\(PYTHONPATH=.*\)/\1/' /etc/odemis.conf
     fi
 
@@ -66,6 +110,7 @@ enable_dev_mode() {
         echo "ERROR: Failed to enable PYTHONPATH in odemis.conf for development mode."
         exit 1
     fi
+    echo "Development mode enabled. Odemis will now use the development version from $ODEMIS_DEV_PATH."
 }
 
 disable_dev_mode() {
@@ -82,7 +127,7 @@ enable_proposed_mode() {
 
     # Add the proposed PPA
     # (it also refreshes the package lists)
-    sudo add-apt-repository -y ppa:delmic-soft/odemis-proposed
+    sudo add-apt-repository -y ppa:${PPA_PROPOSED_NAME}
 
     # Upgrade/install the odemis package
     sudo apt-get install odemis
@@ -91,8 +136,12 @@ enable_proposed_mode() {
 disable_proposed_mode() {
     echo "Disabling proposed mode..."
 
+    # TODO: handle DEB822 sources files (Ubuntu 24.04 and later) => Just use add-apt-repository --remove -y ppa:${PPA_PROPOSED_NAME}
     # Comment out odemis-proposed lines in apt sources
     sudo sed -i '/^deb.*delmic-soft\/odemis-proposed/s/^/# /' /etc/apt/sources.list /etc/apt/sources.list.d/*.list
+
+    # Just in case, make sure the stable PPA is enabled
+    sudo add-apt-repository -y ppa:${PPA_STABLE_NAME}
 
     # Update package lists
     sudo apt-get update
@@ -192,11 +241,20 @@ choice=$(zenity --list --radiolist \
 echo "Selected Odemis channel: $choice"
 
 if [[ -z "$choice" || "$choice" == "$current_channel" ]]; then
-    echo "No change made"
+    echo "No change requested"
     exit 0
 fi
 
 # TRICK: changing the channel requires root privileges, so we need to run the command with sudo.
 # It's not possible to run the select_channel() function directly with sudo. So instead we call
 # this script again with the selected channel as an argument.
-pkexec "$0" --select "$choice"
+# Need the "or" to avoid exiting the script immediately on failure
+pkexec_status=0
+pkexec "$0" --select "$choice" || pkexec_status=$?
+
+# Show a dialog box to indicate the change is done
+if [[ $pkexec_status -eq 0 ]]; then
+    zenity --info --title="Odemis Channel Updated" --text="Odemis has been updated to the '$choice' channel and is ready to use."
+else
+    echo "Failed to change to channel '$choice'. Please check the output for errors."
+fi
